version: 0.2

env:
  secrets-manager:
    # Format: ENV_VAR_NAME: "SecretName:KeyInsideSecret"
    DOCKERHUB_USERNAME: "docker_credentials:DOCKER_HUB_USERNAME"
    DOCKERHUB_PASSWORD: "docker_credentials:DOCKER_HUB_PASSWORD"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      # Use --password-stdin to avoid exposing the password in logs
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - docker build -t braintaskapp:latest .
      - docker tag braintaskapp:latest koventhan/braintaskapp:latest
      - echo "Pushing the Docker image..."
      - docker push koventhan/braintaskapp:latest
  post_build:
    commands:
      - pwd
      - ls -ltr
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml